# namespace: fastapi-prod
resources:
- ../../base
- route.yaml

images:
- name: quay.io/mukeshs1306/py-fastapi-helloworld
  newName: quay.io/mukeshs1306/py-fastapi-helloworld
  newTag: 95119bb37c5dec23e0f3c2a77927bab0eb68f54e

commonLabels:
  environment: prod

configMapGenerator:
- literals:
  - DISPLAY_TEXT="Hello from Production!"
  - IMAGE_PATH="/app/rh-developer.jpg"
  name: fastapi-helloworld-config

generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
